apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'coap-server'
        static_configs:
          - targets: ['10.96.140.216:8000']  # Replace with your CoAP server's IP and port
        scheme: http
        metrics_path: /metrics