# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .

# Install the required Python packages
RUN pip install paho-mqtt

# Run publish_weather.py when the container launches
CMD ["python", "publish_weather.py"]
