# Use a lightweight base image
FROM python:3.9-alpine

# Set the working directory in the container
WORKDIR /app

# Copy only the necessary file
COPY coap_client.py ./

# Install the required Python packages
RUN pip install --no-cache-dir aiocoap

# Run coap_client.py when the container launches
CMD ["python", "coap_client.py"]