apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cmqtt-broker-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mqtt-broker
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80