apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-publisher
  template:
    metadata:
      labels:
        app: weather-publisher
    spec:
      containers:
      - name: weather-publisher
        image: affaan038/local-weather-publisher:latest